# Generated by Django 4.2.16 on 2025-01-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmanagement',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Refused', 'Refused'), ('Refused', 'Refused'), ('Claimed', 'Claimed'), ('Unclaimed', 'Unclaimed')], default='Unclaimed', max_length=50),
        ),
    ]
