# Generated by Django 4.2.16 on 2025-01-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sms', '0003_rename_trx_id_smsmanagement_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmanagement',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('claimed', 'claimed'), ('unclaimed', 'unclaimed')], default='Unclaimed', max_length=50),
        ),
    ]
