# Generated by Django 4.2.16 on 2025-01-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sms', '0004_alter_smsmanagement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmanagement',
            name='amount',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='smsmanagement',
            name='balance',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='smsmanagement',
            name='fee',
            field=models.CharField(max_length=10),
        ),
    ]
