# Generated by Django 4.2.16 on 2025-01-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sms', '0006_alter_smsmanagement_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmanagement',
            name='txn_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
