# Generated by Django 4.2.16 on 2025-01-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settlement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('pending', 'pending'), ('failed', 'failed')], default='pending', max_length=10),
        ),
    ]
