# Generated by Django 4.2.16 on 2025-01-26 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0054_alter_agentprofile_created_by_and_more'),
        ('app_settlement', '0003_alter_settlement_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settlement',
            old_name='amount_after_fees',
            new_name='amount_after_commission',
        ),
        migrations.AddField(
            model_name='settlement',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_profile.merchantwallet'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='amount',
            field=models.FloatField(),
        ),
    ]
