# Generated by Django 4.2.16 on 2025-01-27 05:32

from django.db import migrations, models
import utils.unique_default


class Migration(migrations.Migration):

    dependencies = [
        ('app_settlement', '0006_settlement_amount_in_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='txn_id',
            field=models.CharField(default=utils.unique_default.get_unique_default, max_length=20, unique=True),
        ),
    ]
