# Generated by Django 4.2.16 on 2025-01-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settlement', '0007_alter_settlement_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='txn_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
