# Generated by Django 4.2.16 on 2025-01-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settlement', '0008_alter_settlement_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('failed', 'failed')], default='pending', max_length=10),
        ),
    ]
