# Generated by Django 4.2.16 on 2025-01-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settlement', '0009_alter_settlement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='exchange_rate',
            field=models.FloatField(default=0),
        ),
    ]
