version: '3.9'

services:
  django:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=optixpay_backend.settings
    volumes:
      - .:/app
    restart: always
