version: '3.9'

services:
  django:
    command: >
      gunicorn --timeout 120 --workers 3 optixpay_backend.wsgi:application --bind 0.0.0.0:8000
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=optixpay_backend.settings
    volumes:
      - .:/app
    restart: always
