# Generated by Django 4.2.16 on 2024-12-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktypemodel',
            name='name',
            field=models.CharField(help_text='Name of the bank type, e.g., Bkash, Rocket, Nagad', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='banktypemodel',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_name_category'),
        ),
    ]
