# Generated by Django 4.2.16 on 2024-12-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0002_alter_banktypemodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktypemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
