# Generated by Django 4.2.16 on 2024-12-30 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_deposit', '0005_alter_deposit_bank'),
        ('app_bank', '0004_agentbankmodel_remove_bankmodel_agent_and_more'),
        ('app_profile', '0008_alter_profile_unique_id_alter_wallet_bank_and_more'),
        ('app_withdraw', '0004_alter_withdraw_bank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankModel',
        ),
        migrations.AddField(
            model_name='agentbankmodel',
            name='agent',
            field=models.ForeignKey(help_text='Agent linked to the bank', on_delete=django.db.models.deletion.CASCADE, related_name='banks_agent', to='app_profile.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentbankmodel',
            name='bank_type',
            field=models.ForeignKey(help_text='Type of the bank', on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='app_bank.banktypemodel'),
        ),
        migrations.AddField(
            model_name='agentbankmodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='agentbankmodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_deposit.currency'),
        ),
        migrations.AddField(
            model_name='agentbankmodel',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
    ]
