# Generated by Django 4.2.16 on 2024-12-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0005_delete_bankmodel_agentbankmodel_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentbankmodel',
            name='master_password',
            field=models.CharField(blank=True, help_text='Master password', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agentbankmodel',
            name='master_username',
            field=models.CharField(blank=True, help_text='Master username', max_length=50, null=True),
        ),
    ]
