# Generated by Django 4.2.16 on 2025-01-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0007_alter_agentbankmodel_daily_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentbankmodel',
            name='currency',
        ),
    ]
