# Generated by Django 4.2.16 on 2025-01-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0008_remove_agentbankmodel_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentbankmodel',
            name='account_number',
            field=models.CharField(max_length=50),
        ),
    ]
