# Generated by Django 4.2.16 on 2025-01-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0009_alter_agentbankmodel_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentbankmodel',
            name='balance',
            field=models.FloatField(default=0.0, help_text='Balance'),
        ),
    ]
