# Generated by Django 4.2.16 on 2025-01-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0010_agentbankmodel_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentbankmodel',
            name='deposit_commission',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='agentbankmodel',
            name='withdraw_commission',
            field=models.FloatField(default=5.0),
        ),
    ]
