# Generated by Django 4.2.16 on 2025-01-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0012_banktypemodel_currency_alter_banktypemodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktypemodel',
            name='category',
            field=models.CharField(choices=[('p2p', 'p2p'), ('p2c', 'p2c')], default=3, help_text='Category of the bank type', max_length=3),
        ),
    ]
