# Generated by Django 4.2.16 on 2025-01-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0013_alter_banktypemodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentbankmodel',
            name='usage_for',
            field=models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal')], default='deposit', help_text='Usage for', max_length=100),
        ),
    ]
