# Generated by Django 4.2.16 on 2025-01-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0014_agentbankmodel_usage_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentbankmodel',
            name='usage_for',
            field=models.CharField(choices=[('deposit', 'deposit'), ('withdraw', 'withdraw')], default='deposit', help_text='Usage for', max_length=100),
        ),
    ]
