# Generated by Django 4.2.16 on 2025-01-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0016_alter_agentbankmodel_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktypemodel',
            name='category',
            field=models.CharField(choices=[('p2p', 'p2p'), ('p2c', 'p2c')], default='p2c', help_text='Category of the bank type', max_length=3),
        ),
    ]
