# Generated by Django 4.2.16 on 2025-01-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0018_agentbankmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentbankmodel',
            name='app_key',
            field=models.CharField(blank=True, help_text='API key for the application', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agentbankmodel',
            name='secret_key',
            field=models.CharField(blank=True, help_text='Secret key for the application', max_length=255, null=True),
        ),
    ]
