# Generated by Django 4.2.16 on 2025-02-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0019_alter_agentbankmodel_app_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentbankmodel',
            name='daily_limit',
            field=models.FloatField(default=1, help_text='Daily transaction limit'),
        ),
        migrations.AlterField(
            model_name='agentbankmodel',
            name='daily_usage',
            field=models.FloatField(default=1, help_text='Daily usage so far'),
        ),
        migrations.AlterField(
            model_name='agentbankmodel',
            name='maximum_amount',
            field=models.FloatField(default=1, help_text='Maximum amount allowed'),
        ),
        migrations.AlterField(
            model_name='agentbankmodel',
            name='minimum_amount',
            field=models.FloatField(default=1, help_text='Minimum amount allowed'),
        ),
        migrations.AlterField(
            model_name='agentbankmodel',
            name='monthly_limit',
            field=models.FloatField(default=1, help_text='Monthly transaction limit'),
        ),
        migrations.AlterField(
            model_name='agentbankmodel',
            name='monthly_usage',
            field=models.FloatField(default=1, help_text='Monthly usage so far'),
        ),
    ]
