# Generated by Django 4.2.16 on 2024-12-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('BD', 'Bangladesh'), ('US', 'United States'), ('IN', 'India'), ('UK', 'United Kingdom'), ('CA', 'Canada')], max_length=25, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Merchant', 'Merchant'), ('Agent', 'Agent')], default='Agent', max_length=20, verbose_name='Profile_type'),
        ),
    ]
