# Generated by Django 4.2.16 on 2024-12-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0002_alter_profile_country_alter_profile_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='agent_da62592daa', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Merchant', 'Merchant'), ('Agent', 'Agent'), ('Staff', 'Staff')], default='Agent', max_length=20, verbose_name='Profile_type'),
        ),
    ]
