# Generated by Django 4.2.16 on 2024-12-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0005_alter_merchantprofile_status_alter_profile_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Hold', 'Hold')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='agent_520a299f3a', max_length=100, unique=True),
        ),
    ]
