# Generated by Django 4.2.16 on 2024-12-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0003_alter_banktypemodel_is_active'),
        ('app_profile', '0006_alter_merchantprofile_status_alter_profile_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='merchant_wallet',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='payment_methods',
        ),
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='agent_af14249c55', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='merchant_wallet',
            field=models.ManyToManyField(blank=True, related_name='merchant_profiles', to='app_profile.wallet'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, related_name='merchant_payment_method', to='app_bank.banktypemodel'),
        ),
    ]
