# Generated by Django 4.2.16 on 2024-12-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0008_alter_profile_unique_id_alter_wallet_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='agent_cdc6861334', max_length=100, unique=True),
        ),
    ]
