# Generated by Django 4.2.16 on 2024-12-30 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_bank', '0006_agentbankmodel_master_password_and_more'),
        ('app_profile', '0009_agentprofile_name_agentprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bank.banktypemodel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'merchant_wallet',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='agent_facb9127ed', max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='merchant_wallet',
            field=models.ManyToManyField(blank=True, related_name='merchant_profiles', to='app_profile.merchantwallet'),
        ),
    ]
