# Generated by Django 4.2.16 on 2024-12-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0010_merchantwallet_alter_profile_unique_id_delete_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantwallet',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='agent_6e354823e1', max_length=100, unique=True),
        ),
    ]
