# Generated by Django 4.2.16 on 2025-01-01 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_deposit', '0006_alter_deposit_agent_commission_and_more'),
        ('app_profile', '0011_alter_merchantwallet_balance_alter_profile_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='agent_2267c1e1cc', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='CurrencyConvertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('base_currency_amount', models.FloatField(default=0)),
                ('to_currency_amount', models.FloatField(default=0)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_conversions', to='app_deposit.currency')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_conversions', to='app_deposit.currency')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'currency_conversion',
            },
        ),
        migrations.AddField(
            model_name='merchantwallet',
            name='currency_conversion',
            field=models.ManyToManyField(blank=True, related_name='merchant_wallet', to='app_profile.currencyconvertion'),
        ),
    ]
