# Generated by Django 4.2.16 on 2025-01-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0012_alter_profile_unique_id_currencyconvertion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='agent_cc4be8142d', max_length=100, unique=True),
        ),
    ]
