# Generated by Django 4.2.16 on 2025-01-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0017_alter_profile_unique_id_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='agent_e113a89dcf', max_length=100, unique=True),
        ),
    ]
