# Generated by Django 4.2.16 on 2025-01-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0019_alter_profile_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='prepayment_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='agent_3d41f9722b', max_length=100, unique=True),
        ),
    ]
