# Generated by Django 4.2.16 on 2025-01-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0020_agentprofile_prepayment_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='agent_5e9070a569', max_length=100, unique=True),
        ),
    ]
