# Generated by Django 4.2.16 on 2025-01-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_deposit', '0006_alter_deposit_agent_commission_and_more'),
        ('app_profile', '0023_alter_profile_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_deposit.currency'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='agent_eabb09d45b', max_length=100, unique=True),
        ),
    ]
