# Generated by Django 4.2.16 on 2025-01-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0025_alter_profile_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='agent_6e1b05d999', max_length=100, unique=True),
        ),
    ]
