# Generated by Django 4.2.16 on 2025-01-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0028_alter_profile_unique_id_alter_staffprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='agent_b955a094d3', max_length=100, unique=True),
        ),
    ]
