# Generated by Django 4.2.16 on 2025-01-20 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_deposit', '0007_alter_deposit_agent_id_alter_deposit_merchant_id'),
        ('app_profile', '0048_remove_profile_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('base_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_conversions', to='app_deposit.currency')),
            ],
            options={
                'db_table': 'currency_conversion_based_on_wallet',
            },
        ),
        migrations.RemoveField(
            model_name='merchantwallet',
            name='currency_conversion',
        ),
        migrations.AddField(
            model_name='merchantwallet',
            name='wallet_base_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_base_conversions', to='app_deposit.currency'),
        ),
        migrations.DeleteModel(
            name='CurrencyConvertion',
        ),
        migrations.AddField(
            model_name='currencyconversion',
            name='merchant_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_conversions', to='app_profile.merchantwallet'),
        ),
        migrations.AddField(
            model_name='currencyconversion',
            name='to_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_conversions', to='app_deposit.currency'),
        ),
        migrations.AlterUniqueTogether(
            name='currencyconversion',
            unique_together={('base_currency', 'to_currency', 'merchant_wallet')},
        ),
    ]
