# Generated by Django 4.2.16 on 2025-01-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0049_currencyconversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='is_negative_transaction_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
