# Generated by Django 4.2.16 on 2025-01-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0050_merchantprofile_is_negative_transaction_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='is_negative_transaction_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
