# Generated by Django 4.2.16 on 2025-01-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0052_merchantwallet_deposit_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('hold', 'hold')], default='Active', max_length=255),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('hold', 'hold')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('rejected', 'rejected'), ('hold', 'hold')], default='Pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('hold', 'hold')], default='Active', max_length=120),
        ),
    ]
