# Generated by Django 4.2.16 on 2025-01-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0054_alter_agentprofile_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantwallet',
            name='settlement_commission',
            field=models.FloatField(default=2.5),
        ),
    ]
