# Generated by Django 4.2.16 on 2025-02-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0055_merchantwallet_settlement_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('hold', 'hold')], default='active', max_length=255),
        ),
    ]
