# Generated by Django 4.2.16 on 2025-01-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0015_alter_profile_unique_id'),
        ('app_prepayment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepayment',
            name='agent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepayment_agent', to='app_profile.agentprofile'),
        ),
    ]
