# Generated by Django 4.2.16 on 2025-01-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prepayment', '0002_alter_prepayment_agent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prepayment',
            old_name='amount_bdt',
            new_name='converted_amount',
        ),
    ]
