# Generated by Django 4.2.16 on 2025-01-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prepayment', '0003_rename_amount_bdt_prepayment_converted_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepayment',
            name='order_id',
        ),
    ]
