# Generated by Django 4.2.16 on 2025-01-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prepayment', '0004_remove_prepayment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='payment_id',
            field=models.CharField(default='...', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prepayment',
            name='platform_id',
            field=models.CharField(default='000', max_length=100),
            preserve_default=False,
        ),
    ]
