# Generated by Django 4.2.16 on 2025-01-16 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prepayment', '0005_prepayment_payment_id_prepayment_platform_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepayment',
            options={},
        ),
        migrations.AlterModelTable(
            name='prepayment',
            table='prepayment',
        ),
    ]
