# Generated by Django 4.2.16 on 2025-01-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prepayment', '0006_alter_prepayment_options_alter_prepayment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed')], max_length=100),
        ),
    ]
