# Generated by Django 4.2.16 on 2025-01-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prepayment', '0008_alter_prepayment_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
