# Generated by Django 4.2.16 on 2024-12-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currencies'},
        ),
        migrations.AlterModelTable(
            name='currency',
            table='currency',
        ),
    ]
