# Generated by Django 4.2.16 on 2024-12-30 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0004_agentbankmodel_remove_bankmodel_agent_and_more'),
        ('app_deposit', '0004_alter_currency_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_deposits', to='app_bank.agentbankmodel'),
        ),
    ]
