# Generated by Django 4.2.16 on 2024-12-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deposit', '0005_alter_deposit_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='agent_commission',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='merchant_commission',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='requested_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='sent_amount',
            field=models.FloatField(default=0),
        ),
    ]
