# Generated by Django 4.2.16 on 2025-01-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deposit', '0007_alter_deposit_agent_id_alter_deposit_merchant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='requested_amount',
            new_name='actual_received_amount',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='sent_currency',
            new_name='received_currency',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='sent_amount',
            new_name='sending_amount',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='requested_currency',
            new_name='sending_currency',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('successful', 'successful'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('expired', 'expired'), ('under Review', 'under Review'), ('on Hold', 'on Hold'), ('declined', 'declined')], default='Pending', max_length=20),
        ),
    ]
