# Generated by Django 4.2.16 on 2025-01-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deposit', '0008_rename_requested_amount_deposit_actual_received_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='call_back_url',
            field=models.CharField(default='https://google.com', max_length=255),
        ),
    ]
