# Generated by Django 4.2.16 on 2025-01-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deposit', '0009_deposit_call_back_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='oxp_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='txn_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
