# Generated by Django 4.2.16 on 2025-01-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deposit', '0010_alter_deposit_oxp_id_alter_deposit_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='oxp_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='txn_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
