# Generated by Django 4.2.16 on 2025-01-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deposit', '0011_alter_deposit_oxp_id_alter_deposit_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
