# Generated by Django 4.2.16 on 2025-01-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deposit', '0013_alter_currency_created_by_alter_currency_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('assigned', 'assigned'), ('success', 'success'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('expired', 'expired'), ('under Review', 'under Review'), ('on Hold', 'on Hold'), ('declined', 'declined')], default='Pending', max_length=20),
        ),
    ]
