# Generated by Django 4.2.16 on 2024-12-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_deposit', '0003_rename_agent_deposit_agent_id_and_more'),
        ('app_withdraw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdraw',
            old_name='agent',
            new_name='agent_id',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='merchant',
            new_name='merchant_id',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='receiver_no',
            new_name='receiver_account',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='sender_no',
            new_name='sender_account',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='received_amount',
            new_name='sent_amount',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='customer',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='customer_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw',
            name='requested_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_currency_withdraw', to='app_deposit.currency'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='sent_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_currency_withdraw', to='app_deposit.currency'),
        ),
    ]
