# Generated by Django 4.2.16 on 2024-12-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_withdraw', '0004_alter_withdraw_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='agent_commission',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='merchant_commission',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='requested_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='sent_amount',
            field=models.FloatField(default=0),
        ),
    ]
