# Generated by Django 4.2.16 on 2025-01-14 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_withdraw', '0005_alter_withdraw_agent_commission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdraw',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='last_updated',
        ),
    ]
