# Generated by Django 4.2.16 on 2025-01-14 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0030_alter_profile_unique_id'),
        ('app_withdraw', '0006_alter_withdraw_options_remove_withdraw_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='agent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_withdraw', to='app_profile.agentprofile'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='merchant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_withdraw', to='app_profile.merchantprofile'),
        ),
    ]
