# Generated by Django 4.2.16 on 2025-01-17 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0040_alter_profile_unique_id'),
        ('app_bank', '0008_remove_agentbankmodel_currency'),
        ('app_withdraw', '0007_alter_withdraw_agent_id_alter_withdraw_merchant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_withdraw', to='app_bank.agentbankmodel'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='merchant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_withdraw', to='app_profile.merchantprofile'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='oxp_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='receiver_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='sender_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='txn_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
