# Generated by Django 4.2.16 on 2025-01-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_withdraw', '0008_alter_withdraw_bank_alter_withdraw_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Successful', 'Successful'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
