# Generated by Django 4.2.16 on 2025-01-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_withdraw', '0009_alter_withdraw_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='cancel_callbackurl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='failed_callbackurl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='success_callbackurl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
