# Generated by Django 4.2.16 on 2025-01-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_withdraw', '0011_alter_withdraw_agent_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='merchant_commission',
            field=models.FloatField(default=5.0),
        ),
    ]
