# Generated by Django 4.2.16 on 2025-01-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_withdraw', '0012_alter_withdraw_merchant_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='agent_amount_after_commission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='merchant_amount_after_commission',
            field=models.FloatField(default=0),
        ),
    ]
