# Generated by Django 4.2.16 on 2025-01-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_withdraw', '0013_withdraw_agent_amount_after_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='agent_balance_should_be',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='merchant_balance_should_be',
            field=models.FloatField(default=0),
        ),
    ]
