# Generated by Django 4.2.16 on 2025-01-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_withdraw', '0015_alter_withdraw_created_by_alter_withdraw_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='converted_amount',
            field=models.FloatField(default=0),
        ),
    ]
