# Generated by Django 4.2.16 on 2025-01-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_withdraw', '0017_alter_withdraw_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('assigned', 'assigned'), ('success', 'success'), ('failed', 'failed')], default='Pending', max_length=20),
        ),
    ]
