from app_deposit.models.deposit import Currency


def get_default_currency():
    return Currency.objects.get_or_create(name='Bangladeshi Taka')[0].pk

currency_codes = [
    ('AFN', 'AFN'),
    ('ALL', 'ALL'),
    ('DZD', 'DZD'),
    ('USD', 'USD'),
    ('EUR', 'EUR'),
    ('AOA', 'AOA'),
    ('XCD', 'XCD'),
    ('ARS', 'ARS'),
    ('AMD', 'AMD'),
    ('AWG', 'AWG'),
    ('AUD', 'AUD'),
    ('AZN', 'AZN'),
    ('BSD', 'BSD'),
    ('BHD', 'BHD'),
    ('BDT', 'BDT'),
    ('BBD', 'BBD'),
    ('BYN', 'BYN'),
    ('BZD', 'BZD'),
    ('XOF', 'XOF'),
    ('BMD', 'BMD'),
    ('BTN', 'BTN'),
    ('BOB', 'BOB'),
    ('BAM', 'BAM'),
    ('BWP', 'BWP'),
    ('BRL', 'BRL'),
    ('GBP', 'GBP'),
    ('BND', 'BND'),
    ('BGN', 'BGN'),
    ('BIF', 'BIF'),
    ('CVE', 'CVE'),
    ('KHR', 'KHR'),
    ('XAF', 'XAF'),
    ('CAD', 'CAD'),
    ('CLP', 'CLP'),
    ('CNY', 'CNY'),
    ('COP', 'COP'),
    ('KMF', 'KMF'),
    ('CDF', 'CDF'),
    ('CRC', 'CRC'),
    ('HRK', 'HRK'),
    ('CUP', 'CUP'),
    ('CZK', 'CZK'),
    ('DKK', 'DKK'),
    ('DJF', 'DJF'),
    ('DOP', 'DOP'),
    ('EGP', 'EGP'),
    ('ERN', 'ERN'),
    ('SZL', 'SZL'),
    ('ETB', 'ETB'),
    ('FJD', 'FJD'),
    ('XPF', 'XPF'),
    ('GMD', 'GMD'),
    ('GEL', 'GEL'),
    ('GHS', 'GHS'),
    ('GIP', 'GIP'),
    ('GTQ', 'GTQ'),
    ('GNF', 'GNF'),
    ('GYD', 'GYD'),
    ('HTG', 'HTG'),
    ('HNL', 'HNL'),
    ('HKD', 'HKD'),
    ('HUF', 'HUF'),
    ('ISK', 'ISK'),
    ('INR', 'INR'),
    ('IDR', 'IDR'),
    ('IRR', 'IRR'),
    ('IQD', 'IQD'),
    ('ILS', 'ILS'),
    ('JMD', 'JMD'),
    ('JPY', 'JPY'),
    ('JOD', 'JOD'),
    ('KZT', 'KZT'),
    ('KES', 'KES'),
    ('KWD', 'KWD'),
    ('KGS', 'KGS'),
    ('LAK', 'LAK'),
    ('LBP', 'LBP'),
    ('LSL', 'LSL'),
    ('LRD', 'LRD'),
    ('LYD', 'LYD'),
    ('MOP', 'MOP'),
    ('MKD', 'MKD'),
    ('MGA', 'MGA'),
    ('MWK', 'MWK'),
    ('MYR', 'MYR'),
    ('MVR', 'MVR'),
    ('MRU', 'MRU'),
    ('MUR', 'MUR'),
    ('MXN', 'MXN'),
    ('MDL', 'MDL'),
    ('MNT', 'MNT'),
    ('MAD', 'MAD'),
    ('MZN', 'MZN'),
    ('MMK', 'MMK'),
    ('NAD', 'NAD'),
    ('NPR', 'NPR'),
    ('ANG', 'ANG'),
    ('NZD', 'NZD'),
    ('NIO', 'NIO'),
    ('NGN', 'NGN'),
    ('NOK', 'NOK'),
    ('OMR', 'OMR'),
    ('PKR', 'PKR'),
    ('PAB', 'PAB'),
    ('PGK', 'PGK'),
    ('PYG', 'PYG'),
    ('PEN', 'PEN'),
    ('PHP', 'PHP'),
    ('PLN', 'PLN'),
    ('QAR', 'QAR'),
    ('RON', 'RON'),
    ('RUB', 'RUB'),
    ('RWF', 'RWF'),
    ('SHP', 'SHP'),
    ('WST', 'WST'),
    ('STN', 'STN'),
    ('SAR', 'SAR'),
    ('RSD', 'RSD'),
    ('SCR', 'SCR'),
    ('SLL', 'SLL'),
    ('SGD', 'SGD'),
    ('SOS', 'SOS'),
    ('ZAR', 'ZAR'),
    ('KRW', 'KRW'),
    ('SSP', 'SSP'),
    ('LKR', 'LKR'),
    ('SDG', 'SDG'),
    ('SRD', 'SRD'),
    ('SEK', 'SEK'),
    ('CHF', 'CHF'),
    ('SYP', 'SYP'),
    ('TWD', 'TWD'),
    ('TJS', 'TJS'),
    ('TZS', 'TZS'),
    ('THB', 'THB'),
    ('TOP', 'TOP'),
    ('TTD', 'TTD'),
    ('TND', 'TND'),
    ('TRY', 'TRY'),
    ('TMT', 'TMT'),
    ('UGX', 'UGX'),
    ('UAH', 'UAH'),
    ('AED', 'AED'),
    ('UYU', 'UYU'),
    ('UZS', 'UZS'),
    ('VUV', 'VUV'),
    ('VES', 'VES'),
    ('VND', 'VND'),
    ('YER', 'YER'),
    ('ZMW', 'ZMW'),
    ('ZWL', 'ZWL')
]

currency_names = [
    ('Afghan Afghani', 'Afghan Afghani'),
    ('Albanian Lek', 'Albanian Lek'),
    ('Algerian Dinar', 'Algerian Dinar'),
    ('US Dollar', 'US Dollar'),
    ('Euro', 'Euro'),
    ('Angolan Kwanza', 'Angolan Kwanza'),
    ('East Caribbean Dollar', 'East Caribbean Dollar'),
    ('Argentine Peso', 'Argentine Peso'),
    ('Armenian Dram', 'Armenian Dram'),
    ('Aruban Florin', 'Aruban Florin'),
    ('Australian Dollar', 'Australian Dollar'),
    ('Azerbaijani Manat', 'Azerbaijani Manat'),
    ('Bahamian Dollar', 'Bahamian Dollar'),
    ('Bahraini Dinar', 'Bahraini Dinar'),
    ('Bangladeshi Taka', 'Bangladeshi Taka'),
    ('Barbadian Dollar', 'Barbadian Dollar'),
    ('Belarusian Ruble', 'Belarusian Ruble'),
    ('Belize Dollar', 'Belize Dollar'),
    ('West African CFA Franc', 'West African CFA Franc'),
    ('Bermudian Dollar', 'Bermudian Dollar'),
    ('Bhutanese Ngultrum', 'Bhutanese Ngultrum'),
    ('Bolivian Boliviano', 'Bolivian Boliviano'),
    ('Bosnia-Herzegovina Convertible Mark', 'Bosnia-Herzegovina Convertible Mark'),
    ('Botswana Pula', 'Botswana Pula'),
    ('Brazilian Real', 'Brazilian Real'),
    ('British Pound', 'British Pound'),
    ('Brunei Dollar', 'Brunei Dollar'),
    ('Bulgarian Lev', 'Bulgarian Lev'),
    ('Burundian Franc', 'Burundian Franc'),
    ('Cabo Verdean Escudo', 'Cabo Verdean Escudo'),
    ('Cambodian Riel', 'Cambodian Riel'),
    ('Central African CFA Franc', 'Central African CFA Franc'),
    ('Canadian Dollar', 'Canadian Dollar'),
    ('Chilean Peso', 'Chilean Peso'),
    ('Chinese Yuan', 'Chinese Yuan'),
    ('Colombian Peso', 'Colombian Peso'),
    ('Comorian Franc', 'Comorian Franc'),
    ('Congolese Franc', 'Congolese Franc'),
    ('Costa Rican Colón', 'Costa Rican Colón'),
    ('Croatian Kuna', 'Croatian Kuna'),
    ('Cuban Peso', 'Cuban Peso'),
    ('Czech Koruna', 'Czech Koruna'),
    ('Danish Krone', 'Danish Krone'),
    ('Djiboutian Franc', 'Djiboutian Franc'),
    ('Dominican Peso', 'Dominican Peso'),
    ('Egyptian Pound', 'Egyptian Pound'),
    ('Eritrean Nakfa', 'Eritrean Nakfa'),
    ('Eswatini Lilangeni', 'Eswatini Lilangeni'),
    ('Ethiopian Birr', 'Ethiopian Birr'),
    ('Fijian Dollar', 'Fijian Dollar'),
    ('CFP Franc', 'CFP Franc'),
    ('Gambian Dalasi', 'Gambian Dalasi'),
    ('Georgian Lari', 'Georgian Lari'),
    ('Ghanaian Cedi', 'Ghanaian Cedi'),
    ('Gibraltar Pound', 'Gibraltar Pound'),
    ('Guatemalan Quetzal', 'Guatemalan Quetzal'),
    ('Guinean Franc', 'Guinean Franc'),
    ('Guyanese Dollar', 'Guyanese Dollar'),
    ('Haitian Gourde', 'Haitian Gourde'),
    ('Honduran Lempira', 'Honduran Lempira'),
    ('Hong Kong Dollar', 'Hong Kong Dollar'),
    ('Hungarian Forint', 'Hungarian Forint'),
    ('Icelandic Króna', 'Icelandic Króna'),
    ('Indian Rupee', 'Indian Rupee'),
    ('Indonesian Rupiah', 'Indonesian Rupiah'),
    ('Iranian Rial', 'Iranian Rial'),
    ('Iraqi Dinar', 'Iraqi Dinar'),
    ('Israeli New Shekel', 'Israeli New Shekel'),
    ('Jamaican Dollar', 'Jamaican Dollar'),
    ('Japanese Yen', 'Japanese Yen'),
    ('Jordanian Dinar', 'Jordanian Dinar'),
    ('Kazakhstani Tenge', 'Kazakhstani Tenge'),
    ('Kenyan Shilling', 'Kenyan Shilling'),
    ('Kuwaiti Dinar', 'Kuwaiti Dinar'),
    ('Kyrgyzstani Som', 'Kyrgyzstani Som'),
    ('Lao Kip', 'Lao Kip'),
    ('Lebanese Pound', 'Lebanese Pound'),
    ('Lesotho Loti', 'Lesotho Loti'),
    ('Liberian Dollar', 'Liberian Dollar'),
    ('Libyan Dinar', 'Libyan Dinar'),
    ('Macanese Pataca', 'Macanese Pataca'),
    ('Macedonian Denar', 'Macedonian Denar'),
    ('Malagasy Ariary', 'Malagasy Ariary'),
    ('Malawian Kwacha', 'Malawian Kwacha'),
    ('Malaysian Ringgit', 'Malaysian Ringgit'),
    ('Maldivian Rufiyaa', 'Maldivian Rufiyaa'),
    ('Mauritanian Ouguiya', 'Mauritanian Ouguiya'),
    ('Mauritian Rupee', 'Mauritian Rupee'),
    ('Mexican Peso', 'Mexican Peso'),
    ('Moldovan Leu', 'Moldovan Leu'),
    ('Mongolian Tögrög', 'Mongolian Tögrög'),
    ('Moroccan Dirham', 'Moroccan Dirham'),
    ('Mozambican Metical', 'Mozambican Metical'),
    ('Myanmar Kyat', 'Myanmar Kyat'),
    ('Namibian Dollar', 'Namibian Dollar'),
    ('Nepalese Rupee', 'Nepalese Rupee'),
    ('Netherlands Antillean Guilder', 'Netherlands Antillean Guilder'),
    ('New Zealand Dollar', 'New Zealand Dollar'),
    ('Nicaraguan Córdoba', 'Nicaraguan Córdoba'),
    ('Nigerian Naira', 'Nigerian Naira'),
    ('Norwegian Krone', 'Norwegian Krone'),
    ('Omani Rial', 'Omani Rial'),
    ('Pakistani Rupee', 'Pakistani Rupee'),
    ('Panamanian Balboa', 'Panamanian Balboa'),
    ('Papua New Guinean Kina', 'Papua New Guinean Kina'),
    ('Paraguayan Guarani', 'Paraguayan Guarani'),
    ('Peruvian Sol', 'Peruvian Sol'),
    ('Philippine Peso', 'Philippine Peso'),
    ('Polish Zloty', 'Polish Zloty'),
    ('Qatari Riyal', 'Qatari Riyal'),
    ('Romanian Leu', 'Romanian Leu'),
    ('Russian Ruble', 'Russian Ruble'),
    ('Rwandan Franc', 'Rwandan Franc'),
    ('Saint Helena Pound', 'Saint Helena Pound'),
    ('Samoan Tala', 'Samoan Tala'),
    ('São Tomé and Príncipe Dobra', 'São Tomé and Príncipe Dobra'),
    ('Saudi Riyal', 'Saudi Riyal'),
    ('Serbian Dinar', 'Serbian Dinar'),
    ('Seychellois Rupee', 'Seychellois Rupee'),
    ('Sierra Leonean Leone', 'Sierra Leonean Leone'),
    ('Singapore Dollar', 'Singapore Dollar'),
    ('Somali Shilling', 'Somali Shilling'),
    ('South African Rand', 'South African Rand'),
    ('South Korean Won', 'South Korean Won'),
    ('South Sudanese Pound', 'South Sudanese Pound'),
    ('Sri Lankan Rupee', 'Sri Lankan Rupee'),
    ('Sudanese Pound', 'Sudanese Pound'),
    ('Surinamese Dollar', 'Surinamese Dollar'),
    ('Swedish Krona', 'Swedish Krona'),
    ('Swiss Franc', 'Swiss Franc'),
    ('Syrian Pound', 'Syrian Pound'),
    ('Taiwan Dollar', 'Taiwan Dollar'),
    ('Tajikistani Somoni', 'Tajikistani Somoni'),
    ('Tanzanian Shilling', 'Tanzanian Shilling'),
    ('Thai Baht', 'Thai Baht'),
    ('Tongan Paʻanga', 'Tongan Paʻanga'),
    ('Trinidad and Tobago Dollar', 'Trinidad and Tobago Dollar'),
    ('Tunisian Dinar', 'Tunisian Dinar'),
    ('Turkish Lira', 'Turkish Lira'),
    ('Turkmenistani Manat', 'Turkmenistani Manat'),
    ('Ugandan Shilling', 'Ugandan Shilling'),
    ('Ukrainian Hryvnia', 'Ukrainian Hryvnia'),
    ('United Arab Emirates Dirham', 'United Arab Emirates Dirham'),
    ('Uruguayan Peso', 'Uruguayan Peso'),
    ('Uzbekistani Som', 'Uzbekistani Som'),
    ('Vanuatu Vatu', 'Vanuatu Vatu'),
    ('Venezuelan Bolívar', 'Venezuelan Bolívar'),
    ('Vietnamese Đồng', 'Vietnamese Đồng'),
    ('Yemeni Rial', 'Yemeni Rial'),
    ('Zambian Kwacha', 'Zambian Kwacha'),
    ('Zimbabwean Dollar', 'Zimbabwean Dollar'),
]

