# Generated by Django 4.2.16 on 2025-01-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0005_custompermission_customgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompermission',
            name='permission_type',
            field=models.CharField(choices=[('Create', 'Create'), ('Read', 'Read'), ('Update', 'Update'), ('Delete', 'Delete')], default='Read', max_length=255),
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='all_permissions',
            field=models.ManyToManyField(blank=True, to='app_auth.custompermission', verbose_name='all_permissions'),
        ),
    ]
