# Generated by Django 4.2.16 on 2025-01-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0006_custompermission_permission_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompermission',
            name='permission_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='custompermission',
            unique_together={('permission_name', 'permission_type')},
        ),
    ]
