# Generated by Django 4.2.16 on 2025-01-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0009_alter_customuser_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='group_name',
        ),
    ]
